-- Wprowadzać po insertach z tabeli: [Rola] !!!

-- Co znaczy aktywny?
-- TODO: Zmienić hasło na jakieś hashowanie!

insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (1, 'mhyne0@networkadvertising.org', 'E1H540yaO', 'American', 25, 11, 'Albany', '12247', 518645897, 'Monika', 'Hyne', 1, 1);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (2, 'crobillard1@ask.com', 'sjBIBvM4zyZJ', 'Kenwood', 115, null, 'Passos', '37900-000', 596493367, 'Christyna', 'Robillard', 0, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (3, 'wbehn2@hubpages.com', 'Rxk6Ge5FNt', 'Pawling', 49, null, 'Tianzhuang', '57-167', 872393621, 'Winfield', 'Behn', 1, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (4, 'gkerner3@dailymotion.com', 'Y3P35Fq42m', 'Corry', 23, null, 'Luwu', '57-193', 492126966, 'Ginevra', 'Kerner', 0, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (5, 'cduthie4@usatoday.com', 'hwPJvjWXiZ', 'Mifflin', 89, null, 'Banjarkemuning', '57-962', 569440817, 'Carilyn', 'Duthie', 0, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (6, 'bschultze5@tiny.cc', 'zw7YMsm7', 'Nevada', 110, null, 'Mogi Guaçu', '13840-000', 577459667, 'Bondy', 'Schultze', 1, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (7, 'mwhoston6@360.cn', 'nW8pFtV', 'Beilfuss', 107, null, 'Det Udom', '34160', 846819339, 'Meredeth', 'Whoston', 0, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (8, 'mkynder7@posterous.com', 'mI95Pw', 'Namekagon', 124, 4, 'Maguwon', '57-391', 933623388, 'Mirella', 'Kynder', 0, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (9, 'vsebyer8@chronoengine.com', 'L9HfHwh', 'Morningstar', 108, null, 'Svenljunga', '512 24', 815660766, 'Vivianne', 'Sebyer', 0, 2);
insert into Uzytkownik (id, adres_email, haslo, adres_ulica, adres_kod_budynku, adres_kod_mieszkania, adres_miejscowosc, adres_kod_pocztowy, numer_telefonu, imie, nazwisko, czy_aktywny, id_roli) values (10, 'dmeriot9@si.edu', '1uZ5pb2Fx7W', 'Golf', 45, 18, 'Santa Rosa', '4618', 612182734, 'Danni', 'Meriot', 1, 2);
